theme: minima

title: "ticehurst.com"
author: Bill Ticehurst
email: billti@hotmail.com
description: thoughts on software

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"
#  social_links:
#    twitter: billticehurst
#    github:  billti
url: "https://ticehurst.com"
twitter_username: billticehurst
github_username: billti

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
#  - test.md
#  - v8/overview.md
  - about.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed
